### PR TITLE
Added astyle as external project

### PR DESCRIPTION
**Pull request by RLessmann**
Removed astyle as submodule and readded it as external project with downloading the astyle source code from sourceforge.

### CODE REVIEW

**Comment by gfiumara** [comment]
Didn't we _just_ agree to remove this from the build and run it as pre-commit hooks? I removed it on Friday, styled the source, and added a [CONTRIBUTING.md](https://github.com/usnistgov/NFIQ2/blob/iso_wg3/CONTRIBUTING.md#source-code) with this information.

**Comment by RLessmann** [comment]
Guess I'm confused. Seems to be a misunderstanding. Astyle is not part of the operating system and exists in multiple versions. To have more control over it, it might be good to include AStyle as external project, but do not set the build to do an automatic reformating (different executable names and host platform). As I say, I'm confused...

**Comment by gfiumara** [comment]
I think we should just keep it separate. Yes, `astyle` isn't part of the OS (actually, it _is_ packaged with Ubuntu and as part of MacPorts), but neither is CMake, and we require developers to download the latest version of CMake in order to build. In this case, `astyle` is really only required to make code _changes_. I don't think it makes sense to maintain the `astyle` project as something we need to build. Additionally, we won't be able to support offline builds with the subversion integration. I appreciate the effort, but I don't think this additional dependency is worth taking on.

Because it's part of Ubuntu, we can have Travis CI check for compliance and reject PRs that need modification [as is done here](https://github.com/tklengyel/drakvuf/blob/3adc625dec6bbcf32b6108d5d28352039e29e818/.travis.yml#L29).

**Comment by RLessmann** [comment]
OK, understood. No problem. I will keep the Astyle integration on my private fork. thx

**Pull request closed without merging**
