### PR TITLE
support bmp for cli, add imgcodecs to opencv build

### PR DESCRIPTION
**Pull request by RLessmann**
please add the imgcodecs library to the opencv build, so command line apps can use opencv to load images and do not need to re-integrate opencv for this purpose.

### CODE REVIEW

**Comment by gfiumara** [comment]
Hi @RLessmann, can you confirm this actually does what you want? The top-level `CMakeLists.txt` still has configuration options like `WITH_PNG=OFF BUILD_PNG=OFF`, meaning that the only formats supported by building the `imgcodecs` module are the [built-in types](https://docs.opencv.org/4.x/db/d05/tutorial_config_reference.html#tutorial_config_reference_func_imgcodecs) (notably: BMP and PGM).

I also have some concern that the third-party codecs from OpenCV, if re-enabled, are going to clash with those that are static-linked into `libbiomeval`. We should make a simple test program that uses both libbiomeval image parsing and OpenCV image processing in the same app to confirm nothing bad happens.

**Comment by gfiumara** [comment]
Linking related issue #265.

**Comment by RLessmann** [comment]
The built in types should be efficient enough. I also do not like to add dependencies to the typica third party formats like png. So lets stick with the built in types only.

**Comment by gfiumara** [comment]
@RLessmann Okay, then there should be no issues! Merging.

**Pull request merged**
